version: '3'
services:
    rasa_server:
      container_name: "rasa_server"
      restart: unless-stopped
      user: root
      build: 
        context: Chatbot
        dockerfile: Dockerfile
      volumes:
        - "./Chatbot:/app"
      ports: 
        - "5005:5005"
    action_server:
      container_name: "action_server"
      restart: unless-stopped
      build: 
        context: Chatbot
        dockerfile: ./actions/Dockerfile
      volumes:
        - "./Chatbot/actions:/app/actions"
        - "./Chatbot/data:/app/data"
      ports:
        - "5055:5055"