version: '3.5'
services:
  qanary-pipeline:
    image: qanary/qanary-pipeline:3.8.0
    #network_mode: host
    ports:
      - "8686:8686"
    environment:
      - HOST_IP=141.57.8.18
      - VIRTUOSO_URL=jdbc:virtuoso://demos.swe.htwk-leipzig.de:40142
      - VIRTUOSO_USERNAME=readWrite
      - VIRTUOSO_PASSWORD=PASSWORD
      - SERVER_HOST=http://141.57.8.18
      - SERVER_PORT=8686
      - QANARY_PROCESS_ALLOW-ADDITIONAL-TRIPLES=false
  meaningcloud-ned:
    image: qanary/qanary-component-ned-meaningcloud:3.0.1
    ports:
      - 40116:40116
    # network_mode: host
    restart: always
    environment:
      - SERVER_PORT=40116
      - SPRING_BOOT_ADMIN_URL=http://141.57.8.18:8686
      - SERVER_HOST=http://141.57.8.18
      - SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE-BASE-URL=http://141.57.8.18:40116
  qb-sina:
    image: qanary/qanary-component-qb-sina:3.1.3
    ports:
      - 40119:40119
    # network_mode: host
    restart: always
    environment:
      - SERVER_PORT=40119
      - SPRING_BOOT_ADMIN_URL=http://141.57.8.18:8686
      - SERVER_HOST=http://141.57.8.18
      - SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE-BASE-URL=http://141.57.8.18:40119
  chatbot-ui:
    image: qanary/qanary-ui:latest
    restart: unless-stopped
    ports:
      - "$CHATBOT_UI_PORT:80"
    environment:
      - HOST_IP=$HOST_IP
      - DEFAULT_LANGUAGE="$CHATBOT_UI_DEFAULT_LANGUAGE"
      - CHATBOT_FRONTEND_URL="$CHATBOT_UI_FRONTEND_URL"
      - DEFAULT_CHATBOT_BACKEND_URL="$CHATBOT_UI_DEFAULT_BACKEND_URL"
      - DEFAULT_CHATBOT_COMPONENTS=$CHATBOT_UI_DEFAULT_COMPONENTS
      - INITIAL_QUESTION_PARAMETER_NAME="$CHATBOT_UI_INITIAL_QUESTION_PARAMETER_NAME"
      - DEFAULT_BACKEND_TYPE="$CHATBOT_UI_DEFAULT_BACKEND_TYPE"
  rasa_server:
    container_name: "rasa_server"
    restart: unless-stopped
    user: root
    build: 
      context: Chatbot
      dockerfile: Dockerfile
    volumes:
      - "./Chatbot:/app"
    #network_mode: host
    ports:
      - "5005:5005"
    environment:
      - HOST_IP=$HOST_IP
      - RASA_ACTION_ENDPOINT_HOST=$HOST_IP
  action_server:
    container_name: "action_server"
    restart: unless-stopped
    build: 
      context: Chatbot
      dockerfile: ./actions/Dockerfile
    volumes:
      - "./Chatbot/actions:/app/actions"
      - "./Chatbot/data:/app/data"
    #network_mode: host
    ports:
      - "5055:5055"
    environment:
      - QANARY_IP=$HOST_IP
      - SPARQL_IP=$HOST_IP
      - SPARQL_PORT=8686

volumes:
  artifacts: {}
